symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    # Allow multiple reset requests (remove rate limiting)
    enable_garbage_collection: true
    # Reduce token lifetime to 30 minutes (default is 1 hour)
    lifetime: 1800
