# config/packages/security.yaml
security:
    ########################################################################
    # 1. PASSWORD HASHING & USER PROVIDER
    ########################################################################
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_users:
            entity:
                class: App\Entity\Client
                property: email

    ########################################################################
    # 2. FIREWALLS
    ########################################################################
    firewalls:
        # Static assets & profiler
        dev:
            pattern: '^/(_(profiler|wdt)|css|images|js)/'
            security: false

        # Main application firewall
        main:
            lazy: true
            provider: app_users

            # ---- FORM-LOGIN ----
            form_login:
                login_path:  '/login'          # absolute path!
                check_path:  '/login'
                enable_csrf: true
                default_target_path: '/home'   # where to go *after* login

            # ---- LOGOUT ----
            logout:
                path:   '/logout'
                target: '/home'

    ########################################################################
    # 3. ACCESS CONTROL (first match wins)
    ########################################################################
    access_control:
        # pages everyone may see ------------------------------------------------
        - { path: '^/$',         roles: IS_AUTHENTICATED_ANONYMOUSLY } # <-- root redirect
        - { path: '^/login$',    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/register$', roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # admin area ------------------------------------------------------------
        - { path: '^/admin',     roles: ROLE_ADMIN }

        # everything else requires login ---------------------------------------
        - { path: '^/',          roles: ROLE_USER }
