security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_users:
            entity:
                class: App\Entity\Client
                property: email

    firewalls:
        # static files, profiler, etc.
        dev:
            pattern: '^/(_(profiler|wdt)|css|images|js)/'
            security: false

        # main firewall for the application
        main:
            lazy: true
            provider: app_users

            # ---------- FORM-LOGIN ----------
            form_login:
                login_path:  '/login'      # absolute path (NOT app_login)
                check_path:  '/login'
                enable_csrf: true
                default_target_path: '/home'   # where to go *after* successful login

            # ---------- LOGOUT ----------
            logout:
                path:   '/logout'
                target: '/home'

            # uncomment to enable “remember me”
            # remember_me:
            #     secret:   '%kernel.secret%'
            #     lifetime: 2592000   # 30 days

    # ---------- ACCESS CONTROL ----------
    # the first rule that matches wins
    access_control:
        # public pages
        - { path: '^/login$',    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/register$', roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # admin area
        - { path: '^/admin',     roles: ROLE_ADMIN }

        # everything else requires a logged-in user
        - { path: '^/',          roles: ROLE_USER }

