# .platform.app.yaml
name: app
type: 'php:8.4'

disk: 256

mounts:
  'public/uploads':          # put the writable dir inside public/
    source: local
    source_path: uploads

relationships:
  mysql: 'mysql:mysql'

# ***** add this block *****
web:
  locations:
    "/":
      root: "public"         # doc-root
      passthru: "/index.php" # send everything to the front controller
# ***************************
