name: app
type: 'php:8.4'
disk: 256

mounts:
  'public/uploads': { source: local, source_path: uploads }
  'var':            { source: local, source_path: var }

web:
  locations:
    '/':
      root: 'public'
      passthru: '/index.php'

relationships:
  database: 'database:mysql'

variables:
  env:
    APP_ENV:  'prod'
    APP_DEBUG: 0
