controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

root_to_home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: home
        permanent: true
