"https://www.{default}/":
  type: redirect
  to:   "https://www.{default}/login"

"https://{default}/":
  type: redirect
  to:   "https://{default}/login"

"https://www.{default}/login":
  type: upstream
  upstream: "app:http"

"https://{default}/login":
  type: upstream
  upstream: "app:http"
